package com.app.shopinkarts.response

data class FlashSaleProduct(
    val _id: String,
    val attributes: List<Attribute>,
    val avgRating: Double,
    val categoryId: String,
    val categoryName: String,
    val creationTimeStamp: String,
    val deliveryInstructions: List<String>,
    val description: String,
    val discount: Int,
    val discountType: Int,
    val dispatchDetails: List<String>,
    val flashSaleDiscount: Int,
    val flashSaleDiscountType: String,
    val flashSalePrice: Int,
    val hsnCode: String,
    val isFreeDelivery: Int,
    val manufacturerId: Int,
    val price: Int,
    val priceReselling: Int,
    val productCheckList: ProductCheckList,
    val productId: String,
    val productImages: List<String>,
    val productName: String,
    val reviews: List<Any>,
    val stock: Int,
    val subCategoryId: String,
    val subCategoryName: String,
    val tax: Int,
    val taxType: Int,
    val variantsArr: List<VariantsArr>
)